/*
 * Minimalna konfiguracja mbedTLS dla Bursztyn OS (Bare-Metal).
 * Odcina bibliotekę od standardowych funkcji systemu (libc) i sieci.
 */
#pragma once

// Używamy dedykowanej platformy
#define MBEDTLS_PLATFORM_C
#define MBEDTLS_PLATFORM_MEMORY
#define MBEDTLS_PLATFORM_NO_STD_FUNCTIONS

// Bursztyn OS nie ma libc (malloc/free), uzyjemy wbudowanego w mbedtls alokatora buforowego
#define MBEDTLS_MEMORY_BUFFER_ALLOC_C

// Wyłączamy obsługę dysku, sieci i czasu z Linuxa/Windowsa
#undef MBEDTLS_FS_IO
#undef MBEDTLS_NET_C
#undef MBEDTLS_TIMING_C
#undef MBEDTLS_HAVE_TIME

// Bursztyn OS nie ma /dev/urandom, podepniemy sprzętowy generator procesora (RDRAND)
#define MBEDTLS_NO_PLATFORM_ENTROPY
#define MBEDTLS_ENTROPY_HARDWARE_ALT
#define MBEDTLS_NO_DEFAULT_ENTROPY_SOURCES

// Funkcje, które będą nam potrzebne do HTTPS
#define MBEDTLS_SSL_CLI_C
#define MBEDTLS_SSL_TLS_C
#define MBEDTLS_SSL_PROTO_TLS1_2
#define MBEDTLS_RSA_C
#define MBEDTLS_AES_C
#define MBEDTLS_SHA256_C
#define MBEDTLS_CIPHER_C
#define MBEDTLS_BIGNUM_C
#define MBEDTLS_PK_C
#define MBEDTLS_PKCS1_V15
#define MBEDTLS_X509_CRT_PARSE_C

// Zapobieganie błędom linkera przy braku snprintf
#define MBEDTLS_PLATFORM_SNPRINTF_MACRO  snprintf_dummy
